export const propertyData: Record<string, any> = {
  "grand-hotel": {
    id: "1",
    slug: "grand-hotel",
    name: "Grand Hotel",
    location: "New York, USA",
    price: 150,
    rating: 4.8,
    reviews: 324,
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&sig=2",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&sig=3",
    ],
    description: "A luxurious hotel located in the heart of New York City, offering world-class amenities and exceptional service.",
    amenities: ["Wi-Fi", "Parking", "Restaurant", "Gym", "Spa", "Room Service"],
    rooms: 120,
    type: "Hotel",
    roomsData: [
      { id: 1, name: "Deluxe Room", price: 150, beds: "1 King Bed", size: "300 sq ft", image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800" },
      { id: 2, name: "Executive Suite", price: 250, beds: "1 King Bed + Sofa", size: "500 sq ft", image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800" },
      { id: 3, name: "Presidential Suite", price: 500, beds: "2 King Beds", size: "1000 sq ft", image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800" },
    ],
    attractions: [
      { name: "Central Park", distance: "0.5 miles", description: "Beautiful urban park perfect for walking and relaxation" },
      { name: "Times Square", distance: "1.2 miles", description: "Iconic entertainment hub with theaters and shopping" },
      { name: "Statue of Liberty", distance: "5 miles", description: "Historic monument accessible by ferry" },
      { name: "Metropolitan Museum", distance: "1 mile", description: "World-renowned art museum" },
    ],
    features: [
      { name: "24/7 Concierge", icon: "👨‍💼", description: "Round-the-clock assistance for all your needs" },
      { name: "Fine Dining", icon: "🍽️", description: "Award-winning restaurant with international cuisine" },
      { name: "Spa & Wellness", icon: "🧘", description: "Full-service spa with massage and wellness treatments" },
      { name: "Business Center", icon: "💼", description: "Fully equipped meeting rooms and business facilities" },
      { name: "Fitness Center", icon: "💪", description: "State-of-the-art gym with personal trainers" },
      { name: "Rooftop Pool", icon: "🏊", description: "Stunning rooftop pool with city views" },
    ],
    about: {
      description: "Grand Hotel has been serving guests with excellence since 1920. Located in the heart of Manhattan, we offer a perfect blend of historic charm and modern luxury. Our commitment to exceptional service and attention to detail has made us a preferred choice for travelers from around the world.",
      history: "Established in 1920, Grand Hotel has hosted numerous celebrities, dignitaries, and world leaders. The hotel underwent a major renovation in 2018, preserving its historic character while adding modern amenities.",
      awards: ["AAA Five Diamond Award", "Travel + Leisure World's Best", "Conde Nast Readers' Choice"],
    },
    contact: {
      phone: "+1 (212) 555-0123",
      email: "info@grandhotel.com",
      address: "123 Park Avenue, New York, NY 10001",
      hours: "Front Desk: 24/7 | Restaurant: 6:00 AM - 11:00 PM",
    },
  },
  "beach-resort": {
    id: "2",
    slug: "beach-resort",
    name: "Beach Resort",
    location: "Miami, USA",
    price: 180,
    rating: 4.9,
    reviews: 512,
    images: [
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&sig=2",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&sig=3",
    ],
    description: "Stunning beachfront resort with ocean views and world-class amenities.",
    amenities: ["Wi-Fi", "Beach Access", "Pool", "Restaurant", "Spa", "Water Sports"],
    rooms: 85,
    type: "Resort",
    roomsData: [
      { id: 1, name: "Ocean View Room", price: 180, beds: "1 King Bed", size: "350 sq ft", image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800" },
      { id: 2, name: "Beachfront Suite", price: 320, beds: "1 King Bed + Balcony", size: "600 sq ft", image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800" },
    ],
    attractions: [
      { name: "South Beach", distance: "0.1 miles", description: "Famous beach with white sand and clear waters" },
      { name: "Art Deco District", distance: "0.5 miles", description: "Historic architecture and vibrant nightlife" },
    ],
    features: [
      { name: "Private Beach", icon: "🏖️", description: "Exclusive beach access for guests" },
      { name: "Water Sports", icon: "🏄", description: "Snorkeling, kayaking, and paddleboarding" },
    ],
    about: {
      description: "Beach Resort offers the perfect tropical getaway.",
      history: "Opened in 2010, this modern resort combines luxury with beachfront living.",
      awards: ["Best Beach Resort 2023"],
    },
    contact: {
      phone: "+1 (305) 555-0123",
      email: "info@beachresort.com",
      address: "456 Ocean Drive, Miami Beach, FL 33139",
      hours: "Front Desk: 24/7",
    },
  },
  "mountain-villa": {
    id: "3",
    slug: "mountain-villa",
    name: "Mountain Villa",
    location: "Aspen, USA",
    price: 350,
    rating: 4.7,
    reviews: 89,
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&sig=2",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&sig=3",
    ],
    description: "Private villa with mountain views and luxury amenities.",
    amenities: ["Wi-Fi", "Parking", "Fireplace", "Kitchen", "Hot Tub"],
    rooms: 12,
    type: "Villa",
    roomsData: [
      { id: 1, name: "Master Suite", price: 350, beds: "1 King Bed", size: "400 sq ft", image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800" },
    ],
    attractions: [
      { name: "Ski Resorts", distance: "2 miles", description: "World-class skiing and snowboarding" },
    ],
    features: [
      { name: "Mountain Views", icon: "⛰️", description: "Stunning panoramic mountain views" },
    ],
    about: {
      description: "Mountain Villa offers a secluded luxury experience.",
      history: "Built in 2015, this villa combines modern luxury with natural beauty.",
      awards: [],
    },
    contact: {
      phone: "+1 (970) 555-0123",
      email: "info@mountainvilla.com",
      address: "789 Mountain Road, Aspen, CO 81611",
      hours: "Front Desk: 24/7",
    },
  },
  "city-hotel": {
    id: "4",
    slug: "city-hotel",
    name: "City Hotel",
    location: "San Francisco, USA",
    price: 200,
    rating: 4.6,
    reviews: 267,
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&sig=2",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&sig=3",
    ],
    description: "Modern hotel in downtown San Francisco.",
    amenities: ["Wi-Fi", "Parking", "Restaurant", "Gym"],
    rooms: 200,
    type: "Hotel",
    roomsData: [
      { id: 1, name: "Standard Room", price: 200, beds: "1 Queen Bed", size: "250 sq ft", image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800" },
    ],
    attractions: [
      { name: "Golden Gate Bridge", distance: "3 miles", description: "Iconic suspension bridge" },
    ],
    features: [
      { name: "Downtown Location", icon: "🏙️", description: "Prime location in the heart of the city" },
    ],
    about: {
      description: "City Hotel offers modern comfort in San Francisco.",
      history: "Established in 2012, this hotel provides excellent value in the city center.",
      awards: [],
    },
    contact: {
      phone: "+1 (415) 555-0123",
      email: "info@cityhotel.com",
      address: "321 Market Street, San Francisco, CA 94102",
      hours: "Front Desk: 24/7",
    },
  },
  "lakeside-resort": {
    id: "5",
    slug: "lakeside-resort",
    name: "Lakeside Resort",
    location: "Lake Tahoe, USA",
    price: 220,
    rating: 4.9,
    reviews: 445,
    images: [
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&sig=2",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&sig=3",
    ],
    description: "Peaceful resort by the lake with stunning views.",
    amenities: ["Wi-Fi", "Parking", "Restaurant", "Spa", "Boat Access"],
    rooms: 95,
    type: "Resort",
    roomsData: [
      { id: 1, name: "Lake View Room", price: 220, beds: "1 King Bed", size: "300 sq ft", image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800" },
    ],
    attractions: [
      { name: "Lake Tahoe", distance: "0.2 miles", description: "Beautiful alpine lake" },
    ],
    features: [
      { name: "Lake Access", icon: "🏞️", description: "Direct access to the lake" },
    ],
    about: {
      description: "Lakeside Resort offers tranquility and natural beauty.",
      history: "Opened in 2008, this resort has been a favorite for nature lovers.",
      awards: [],
    },
    contact: {
      phone: "+1 (530) 555-0123",
      email: "info@lakesideresort.com",
      address: "555 Lake Drive, Lake Tahoe, CA 96150",
      hours: "Front Desk: 24/7",
    },
  },
  "desert-oasis": {
    id: "6",
    slug: "desert-oasis",
    name: "Desert Oasis",
    location: "Phoenix, USA",
    price: 190,
    rating: 4.5,
    reviews: 198,
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&sig=2",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&sig=3",
    ],
    description: "Luxury desert resort with spa facilities.",
    amenities: ["Wi-Fi", "Parking", "Restaurant", "Spa", "Pool"],
    rooms: 150,
    type: "Resort",
    roomsData: [
      { id: 1, name: "Desert View Room", price: 190, beds: "1 King Bed", size: "350 sq ft", image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800" },
    ],
    attractions: [
      { name: "Grand Canyon", distance: "200 miles", description: "One of the world's natural wonders" },
    ],
    features: [
      { name: "Desert Spa", icon: "🧖", description: "Luxury spa with desert-inspired treatments" },
    ],
    about: {
      description: "Desert Oasis offers a unique desert luxury experience.",
      history: "Built in 2018, this resort combines modern luxury with desert beauty.",
      awards: [],
    },
    contact: {
      phone: "+1 (602) 555-0123",
      email: "info@desertoasis.com",
      address: "777 Desert Road, Phoenix, AZ 85001",
      hours: "Front Desk: 24/7",
    },
  },
}
